# Type stubs for DataFrameExpectationsSuite
# Auto-generated by scripts/generate_suite_stubs.py
# DO NOT EDIT - Regenerate with: python scripts/generate_suite_stubs.py

from functools import wraps
from typing import Union, Any, Callable, Dict, List, Optional, cast
from dataframe_expectations.core.types import DataFrameLike, TagMatchMode
from dataframe_expectations.core.tagging import TagSet
from dataframe_expectations.registry import DataFrameExpectationRegistry
from dataframe_expectations.core.expectation import DataFrameExpectation
import logging
from dataframe_expectations.result_message import DataFrameExpectationFailureMessage, DataFrameExpectationSuccessMessage
from dataframe_expectations.core.suite_result import SuiteExecutionResult

class DataFrameExpectationsSuiteFailure(Exception):
    """Raised when one or more expectations in the suite fail."""
    def __init__(self, total_expectations: int, failures: List[DataFrameExpectationFailureMessage], result: Optional[SuiteExecutionResult]=None, *args):
        ...
    def __str__(self):
        ...

class DataFrameExpectationsSuiteRunner:
    """
    Immutable runner for executing a fixed set of expectations.
    This class is created by DataFrameExpectationsSuite.build() and
    runs the expectations on provided DataFrames.
    """
    @staticmethod
    def _matches_tag_filter(expectation: Any, filter_tag_set: TagSet, tag_match_mode: TagMatchMode) -> bool:
        """

                Check if an expectation matches the tag filter criteria.

                :param expectation: Expectation instance to check.
                :param filter_tag_set: Tag filter to match against.
                :param tag_match_mode: Match mode - TagMatchMode.ANY (OR) or TagMatchMode.ALL (AND).
                :return: True if expectation matches filter, False otherwise.

        """
        ...
    def __init__(self, expectations: List[Any], suite_name: Optional[str]=None, violation_sample_limit: int=5, tags: Optional[List[str]]=None, tag_match_mode: Optional[TagMatchMode]=None):
        """

                Initialize the runner with a list of expectations and metadata.

                :param expectations: List of expectation instances.
                :param suite_name: Optional name for the suite.
                :param violation_sample_limit: Max number of violation rows to include in results.
                :param tags: Optional tag filters as list of strings in "key:value" format.
                            Example: ["priority:high", "priority:medium"]
                            If None or empty, all expectations will run.
                :param tag_match_mode: How to match tags - TagMatchMode.ANY (OR logic) or TagMatchMode.ALL (AND logic).
                                      Required if tags are provided, must be None if tags are not provided.
                                      - TagMatchMode.ANY: Expectation matches if it has ANY of the filter tags
                                      - TagMatchMode.ALL: Expectation matches if it has ALL of the filter tags
                :raises ValueError: If tag_match_mode is provided without tags, or if tags are provided without tag_match_mode,
                                   or if tag filters result in zero expectations to run.

        """
        ...
    @property
    def selected_expectations_count(self) -> int:
        """
        Return the number of expectations that will run (after filtering).
        """
        ...
    @property
    def total_expectations(self) -> int:
        """
        Return the total number of expectations before filtering.
        """
        ...
    @property
    def get_applied_tags(self) -> TagSet:
        """
        Return the applied tag filters for this runner.
        """
        ...
    def list_all_expectations(self) -> List[str]:
        """

                Return a list of all expectation descriptions before filtering.

                :return: List of all expectation descriptions as strings in the format:
                         "ExpectationName (description)"

        """
        ...
    def list_selected_expectations(self) -> List[str]:
        """

                Return a list of selected expectation descriptions (after filtering).

                :return: List of selected expectation descriptions as strings in the format:
                         "ExpectationName (description)"

        """
        ...
    def run(self, data_frame: DataFrameLike, raise_on_failure: bool=True, context: Optional[Dict[str, Any]]=None) -> SuiteExecutionResult:
        """

                Run all expectations on the provided DataFrame with PySpark caching optimization.

                :param data_frame: The DataFrame to validate.
                :param raise_on_failure: If True (default), raises DataFrameExpectationsSuiteFailure on any failures.
                                        If False, returns SuiteExecutionResult instead.
                :param context: Optional runtime context metadata (e.g., {"job_id": "123", "env": "prod"}).
                :return: None if raise_on_failure=True and all pass, SuiteExecutionResult if raise_on_failure=False.

        """
        ...
    def validate(self, func: Optional[Callable]=None, *, allow_none: bool=False) -> Callable:
        """

                Decorator to validate the DataFrame returned by a function.

                This decorator runs the expectations suite on the DataFrame returned
                by the decorated function. If validation fails, it raises
                DataFrameExpectationsSuiteFailure.

                Example::

                    runner = suite.build()

                    @runner.validate
                    def load_data():
                        return pd.read_csv("data.csv")

                    df = load_data()  # Automatically validated

                    # Allow None returns
                    @runner.validate(allow_none=True)
                    def maybe_load_data():
                        if condition:
                            return pd.read_csv("data.csv")
                        return None

                :param func: Function that returns a DataFrame.
                :param allow_none: If True, allows the function to return None without validation.
                                  If False (default), None will raise a ValueError.
                :return: Wrapped function that validates the returned DataFrame.

        """
        ...

class DataFrameExpectationsSuite:
    """
    A builder for creating expectation suites for validating DataFrames.

    Use this class to add expectations, then call build() to create an
    immutable runner that can execute the expectations on DataFrames.

    Example::

        suite = DataFrameExpectationsSuite(suite_name="user_validation")
        suite.expect_value_greater_than(
            column_name="age",
            value=18,
            tags=["priority:high", "category:compliance"]
        )
        suite.expect_value_less_than(
            column_name="salary",
            value=100000,
            tags=["priority:medium", "category:budget"]
        )
        suite.expect_min_rows(
            min_rows=10,
            tags=["priority:low", "category:data_quality"]
        )

        # Build runner for all expectations (no filtering)
        runner_all = suite.build()
        runner_all.run(df)  # Runs all 3 expectations

        # Build runner for high OR medium priority expectations (OR logic)
        runner_any = suite.build(tags=["priority:high", "priority:medium"], tag_match_mode=TagMatchMode.ANY)
        runner_any.run(df)  # Runs 2 expectations (age and salary checks)

        # Build runner for expectations with both high priority AND compliance category (AND logic)
        runner_and = suite.build(tags=["priority:high", "category:compliance"], tag_match_mode=TagMatchMode.ALL)
        runner_and.run(df)  # Runs 1 expectation (age check - has both tags)
    """
    def __init__(self, suite_name: Optional[str]=None, violation_sample_limit: int=5):
        """

                Initialize the expectation suite builder.

                :param suite_name: Optional name for the suite (useful for logging/reporting).
                :param violation_sample_limit: Max number of violation rows to include in results (default 5).

        """
        ...

    def expect_column_max_between(
        self,
        column_name: str,
        min_value: Union[int, float],
        max_value: Union[int, float],
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the maximum value of a numeric column falls within a specified range

        Categories:
          category: Column Aggregation Expectations
          subcategory: Numerical

        :param column_name: The name of the numeric column to check
        :param min_value: The minimum allowed maximum value
        :param max_value: The maximum allowed maximum value

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_column_mean_between(
        self,
        column_name: str,
        min_value: Union[int, float],
        max_value: Union[int, float],
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the mean (average) of a numeric column falls within a specified range

        Categories:
          category: Column Aggregation Expectations
          subcategory: Numerical

        :param column_name: The name of the numeric column to check
        :param min_value: The minimum allowed mean value
        :param max_value: The maximum allowed mean value

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_column_median_between(
        self,
        column_name: str,
        min_value: Union[int, float],
        max_value: Union[int, float],
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the median of a numeric column falls within a specified range

        Categories:
          category: Column Aggregation Expectations
          subcategory: Numerical

        :param column_name: The name of the numeric column to check
        :param min_value: The minimum allowed median value
        :param max_value: The maximum allowed median value

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_column_min_between(
        self,
        column_name: str,
        min_value: Union[int, float],
        max_value: Union[int, float],
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the minimum value of a numeric column falls within a specified range

        Categories:
          category: Column Aggregation Expectations
          subcategory: Numerical

        :param column_name: The name of the numeric column to check
        :param min_value: The minimum allowed minimum value
        :param max_value: The maximum allowed minimum value

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_column_quantile_between(
        self,
        column_name: str,
        quantile: Union[int, float],
        min_value: Union[int, float],
        max_value: Union[int, float],
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if a specific quantile of a numeric column falls within a specified range

        Categories:
          category: Column Aggregation Expectations
          subcategory: Numerical

        :param column_name: The name of the numeric column to check
        :param quantile: The quantile to calculate (0.0 to 1.0, e.g., 0.5 for median)
        :param min_value: The minimum allowed value for the quantile
        :param max_value: The maximum allowed value for the quantile

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_cross_column_rules(
        self,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Validate that every row obeys a set of cross-column association rules, typically mined from reference data via mine_association_rules.

        Categories:
          category: Column Aggregation Expectations
          subcategory: Any Value

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_distinct_column_values_between(
        self,
        column_name: str,
        min_value: int,
        max_value: int,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if a column has a number of distinct values within a specified range

        Categories:
          category: Column Aggregation Expectations
          subcategory: Unique

        :param column_name: The name of the column to check for distinct values
        :param min_value: The minimum number of distinct values (inclusive)
        :param max_value: The maximum number of distinct values (inclusive)

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_distinct_column_values_equals(
        self,
        column_name: str,
        expected_value: int,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if a column has exactly a specified number of distinct values

        Categories:
          category: Column Aggregation Expectations
          subcategory: Unique

        :param column_name: The name of the column to check for distinct values
        :param expected_value: The expected number of distinct values

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_distinct_column_values_greater_than(
        self,
        column_name: str,
        threshold: int,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if a column has at least a specified number of distinct values

        Categories:
          category: Column Aggregation Expectations
          subcategory: Unique

        :param column_name: The name of the column to check for distinct values
        :param threshold: The minimum number of distinct values (exclusive)

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_distinct_column_values_less_than(
        self,
        column_name: str,
        threshold: int,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if a column has at most a specified number of distinct values

        Categories:
          category: Column Aggregation Expectations
          subcategory: Unique

        :param column_name: The name of the column to check for distinct values
        :param threshold: The maximum number of distinct values (exclusive)

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_max_null_count(
        self,
        column_name: str,
        max_count: int,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the count of null/NaN values in a specific column is below a threshold

        Categories:
          category: Column Aggregation Expectations
          subcategory: Any Value

        :param column_name: The name of the column to check for null count
        :param max_count: The maximum allowed count of null/NaN values

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_max_null_percentage(
        self,
        column_name: str,
        max_percentage: Union[int, float],
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the percentage of null/NaN values in a specific column is below a threshold

        Categories:
          category: Column Aggregation Expectations
          subcategory: Any Value

        :param column_name: The name of the column to check for null percentage
        :param max_percentage: The maximum allowed percentage of null/NaN values (0.0 to 100.0)

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_max_rows(
        self,
        max_rows: int,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the DataFrame has at most a maximum number of rows

        Categories:
          category: DataFrame Aggregation Expectations
          subcategory: Any Value

        :param max_rows: The maximum number of rows expected

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_min_rows(
        self,
        min_rows: int,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the DataFrame has at least a minimum number of rows

        Categories:
          category: DataFrame Aggregation Expectations
          subcategory: Any Value

        :param min_rows: The minimum number of rows expected

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_string_contains(
        self,
        column_name: str,
        substring: str,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the values in a string column contain a specified substring

        Categories:
          category: Column Expectations
          subcategory: String

        :param column_name: The name of the column to check
        :param substring: The substring to search for

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_string_ends_with(
        self,
        column_name: str,
        suffix: str,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the values in a string column end with a specified suffix

        Categories:
          category: Column Expectations
          subcategory: String

        :param column_name: The name of the column to check
        :param suffix: The suffix to search for

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_string_length_between(
        self,
        column_name: str,
        min_length: int,
        max_length: int,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the length of the values in a string column is between two specified lengths

        Categories:
          category: Column Expectations
          subcategory: String

        :param column_name: The name of the column to check
        :param min_length: The minimum length that the values should be
        :param max_length: The maximum length that the values should be

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_string_length_equals(
        self,
        column_name: str,
        length: int,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the length of the values in a string column equals a specified length

        Categories:
          category: Column Expectations
          subcategory: String

        :param column_name: The name of the column to check
        :param length: The length that the values should equal

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_string_length_greater_than(
        self,
        column_name: str,
        length: int,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the length of the values in a string column is greater than a specified length

        Categories:
          category: Column Expectations
          subcategory: String

        :param column_name: The name of the column to check
        :param length: The length that the values should be greater than

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_string_length_less_than(
        self,
        column_name: str,
        length: int,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the length of the values in a string column is less than a specified length

        Categories:
          category: Column Expectations
          subcategory: String

        :param column_name: The name of the column to check
        :param length: The length that the values should be less than

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_string_not_contains(
        self,
        column_name: str,
        substring: str,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the values in a string column do not contain a specified substring

        Categories:
          category: Column Expectations
          subcategory: String

        :param column_name: The name of the column to check
        :param substring: The substring to search for

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_string_starts_with(
        self,
        column_name: str,
        prefix: str,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the values in a string column start with a specified prefix

        Categories:
          category: Column Expectations
          subcategory: String

        :param column_name: The name of the column to check
        :param prefix: The prefix to search for

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_unique_rows(
        self,
        column_names: list,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if all rows in the DataFrame are unique based on specified columns

        Categories:
          category: DataFrame Aggregation Expectations
          subcategory: Unique

        :param column_names: List of column names to check for uniqueness. Empty list checks all columns

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_value_between(
        self,
        column_name: str,
        min_value: Union[int, float],
        max_value: Union[int, float],
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the values in a column are between two specified values

        Categories:
          category: Column Expectations
          subcategory: Numerical

        :param column_name: The name of the column to check
        :param min_value: The minimum value for the range
        :param max_value: The maximum value for the range

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_value_equals(
        self,
        column_name: str,
        value: object,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the values in a column equal a specified value

        Categories:
          category: Column Expectations
          subcategory: Any Value

        :param column_name: The name of the column to check
        :param value: The value to compare against

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_value_greater_than(
        self,
        column_name: str,
        value: Union[int, float],
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the values in a column are greater than a specified value

        Categories:
          category: Column Expectations
          subcategory: Numerical

        :param column_name: The name of the column to check
        :param value: The value to compare against

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_value_greater_than_equals(
        self,
        column_name: str,
        value: Union[int, float],
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the values in a column are greater than or equal to a specified value

        Categories:
          category: Column Expectations
          subcategory: Numerical

        :param column_name: The name of the column to check
        :param value: The value to compare against

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_value_in(
        self,
        column_name: str,
        values: list,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the values in a column are in a specified list of values

        Categories:
          category: Column Expectations
          subcategory: Any Value

        :param column_name: The name of the column to check
        :param values: The list of values to compare against

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_value_less_than(
        self,
        column_name: str,
        value: Union[int, float],
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the values in a column are less than a specified value

        Categories:
          category: Column Expectations
          subcategory: Numerical

        :param column_name: The name of the column to check
        :param value: The value to compare against

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_value_less_than_equals(
        self,
        column_name: str,
        value: Union[int, float],
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the values in a column are less than or equal to a specified value

        Categories:
          category: Column Expectations
          subcategory: Numerical

        :param column_name: The name of the column to check
        :param value: The value to compare against

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_value_not_equals(
        self,
        column_name: str,
        value: object,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the values in a column do not equal a specified value

        Categories:
          category: Column Expectations
          subcategory: Any Value

        :param column_name: The name of the column to check
        :param value: The value to compare against

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_value_not_in(
        self,
        column_name: str,
        values: list,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the values in a column are not in a specified list of values

        Categories:
          category: Column Expectations
          subcategory: Any Value

        :param column_name: The name of the column to check
        :param values: The list of values to compare against

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_value_not_null(
        self,
        column_name: str,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the values in a column are not null

        Categories:
          category: Column Expectations
          subcategory: Any Value

        :param column_name: The name of the column to check

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def expect_value_null(
        self,
        column_name: str,
        tags: Optional[List[str]] = None,
    ) -> DataFrameExpectationsSuite:
        """
        Check if the values in a column are null

        Categories:
          category: Column Expectations
          subcategory: Any Value

        :param column_name: The name of the column to check

        :param tags: Optional tags as list of strings in "key:value" format (e.g., ["priority:high", "env:test"]).

        :return: An instance of DataFrameExpectationsSuite.
        """
        ...

    def __getattr__(self, name: str):
        """

                Dynamically create expectation methods.

                This is called when Python can't find an attribute through normal lookup.
                We use it to generate expect_* methods on-the-fly from the registry.

        """
        ...
    def _create_expectation_method(self, suite_method_name: str):
        """

                Create a dynamic expectation method.

                Returns a closure that captures the suite_method_name and self.

        """
        ...
    def build(self, tags: Optional[List[str]]=None, tag_match_mode: Optional[TagMatchMode]=None) -> DataFrameExpectationsSuiteRunner:
        """

                Build an immutable runner from the current expectations.

                This creates a snapshot of the current expectations in the suite.
                You can continue to add more expectations to this suite and build
                new runners without affecting previously built runners.

                :param tags: Optional tag filters as list of strings in "key:value" format.
                            Example: ["priority:high", "priority:medium"]
                            If None or empty, all expectations will be included.
                :param tag_match_mode: How to match tags - TagMatchMode.ANY (OR logic) or TagMatchMode.ALL (AND logic).
                                      Required if tags are provided, must be None if tags are not provided.
                                      - TagMatchMode.ANY: Include expectations with ANY of the filter tags
                                      - TagMatchMode.ALL: Include expectations with ALL of the filter tags
                :return: An immutable DataFrameExpectationsSuiteRunner instance.
                :raises ValueError: If no expectations have been added, if tag_match_mode validation fails,
                                   or if no expectations match the tag filters.

        """
        ...
